### ISSUE TITLE
PR全程代码流程实现

### ISSUE THREAD

**Issue by MUDloki** [UESTC-LIMIT/Progress-Management#14]
1. 我需要写哪些代码
   1. 操作系统框架
      1. 通讯部分：上层结构版以及TR车
      2. 闭环任务部分
      3. 换场任务
   2. 变量规划
      1. 位置
      2. 底盘以及上层结构的状态
      3. 接收到的数据
   3. 各个硬件的底层代码
      1. CAN通讯
      2. Elmo
      3. 3508
      4. 触控开关
      5. 气缸
   4. 路径规划状态机（上层以及通讯都用printf代替）
      1. 正常阶段
      2. 重启阶段
   5. 加入上层结构版及其代码
2. 整理步骤
   1. 整理文件（完成）
   2. 整理框架（完成）
   3. 整理hardware代码（完成）
   4. 整理变量
      1. 握手变量：与上层结构板子与TR车进行握手（完成）
      2. 自检任务循环：板子状态改变（完成）
      3. 取消轮组初始化（完成）
      4. Wheel_VD_Cal();速度解算改为全向轮（坐标系未统一）
      5. Send_Spd2Wheel();发送指令改为全向轮（完成）
      6. 统一指令

**Comment by allensted** [comment]
1. 我需要写哪些代码

   1. 操作系统框架
      1. 通讯部分：上层结构版以及TR车
      2. 闭环任务部分
      3. 换场任务
   2. 变量规划
      1. 位置
      2. 底盘以及上层结构的状态
      3. 接收到的数据
   3. 各个硬件的底层代码
      1. CAN通讯
      2. Elmo
      3. 3508
      4. 触控开关
      5. 气缸
   4. 路径规划状态机（上层以及通讯都用printf代替）
      1. 正常阶段
      2. 重启阶段
   5. 加入上层结构版及其代码

2. 整理步骤

   1. 整理文件（完成）
   2. 整理框架（完成）
   3. 整理hardware代码（完成）
   4. 整理变量
      1. 握手变量：与上层结构板子与TR车进行握手（完成）
      2. 自检任务循环：板子状态改变（完成）
      3. 取消轮组初始化（完成）
      4. Wheel_VD_Cal();速度解算改为全向轮（完成）
      5. Send_Spd2Wheel();发送指令改为全向轮（完成）
      6. 统一指令
         1. CANID统一（已完成）
         2. 名称统一（已完成）

3. 测试步骤

   1. 测试代码控制30电机（已完成）

      1. elmo初始化失败：

         因为elmo的初始化需要初始化TIM7来发送CAN报文，因此主控板里面不能用TIM7来用作检测心跳了

         **至于RC_elmo为什么在主控板里不能用我不知道为啥**

         反正不是elmo挂载数量的问题，浩哥有时间改一下RC_elmo这个库吧 ，移植性不高（有变量冲突），而且会出一些莫名其妙的bug

         问题解决：后来我换了之前PR全向轮主控里面的elmo.c，elmo.h 可以控制30了。

      2. 修改被占用的TIM7为TIM5

   2. 测试全向轮方向解算（已完成）

   3. 测试自检函数通讯上层结构板

      1. 握手信号：

         发现握手信号通讯不上：过滤器设置的问题，一定要保证大主控发给其他轮组也好，上层结构也好的个位数必须是其ID号，不然过滤器会把它过滤掉

         **逻辑分析仪好像坏了，检测出的CAN ID有问题**

      2. 自检函数

         注意过滤器即可

      

   4. 测试气缸（已完成）

   5. 测试触控开关（已完成）
![IMG_20200617_155827](https://user-images.githubusercontent.com/55796598/84871949-c640ee00-b0b3-11ea-9a45-804b7dd107d9.jpg)

   6. 测试代码逻辑

   7. 测试陀螺仪与正交编码器

   8. 加入换场板子

   9. 测试代码

**Comment by allensted** [comment]
主控加入了上上层结构的控制代码
上层结构加入3508代码后不能与主控通讯（之前的版本是完全没问题的）

**握手部分出了很奇怪的bug** 
握手的while循环在break后又重新进循环了
照理说握手结束后应该进入自检函数的循环了，robot_init()只会执行一次
也就是在初始化了TIM后再次执行了robot_init()

但是由于主控以为自己已经握手成功 上册结构板子就无法再握手
这样就永远死在握手循环里面了.....
明天逐步解决

**Comment by allensted** [comment]
> 主控加入了上上层结构的控制代码
> 上层结构加入3508代码后不能与主控通讯（之前的版本是完全没问题的）
> 
> **握手部分出了很奇怪的bug**
> 握手的while循环在break后又重新进循环了
> 照理说握手结束后应该进入自检函数的循环了，robot_init()只会执行一次
> 也就是在初始化了TIM后再次执行了robot_init()
> 
> 但是由于主控以为自己已经握手成功 上册结构板子就无法再握手
> 这样就永远死在握手循环里面了.....
> 明天逐步解决

发现原因了，我在与主控通讯的CAN中断里面 有个case没加break，应该是因为这个原因 我无法进入别的中断，然后操作系统就出了bug，导致运行出错

**Comment by allensted** [comment]
主控的流程部分已经完全完成 并且已经测试时没有问题的 我已经上传到github上
现在还有三个地方没完成
1. 上层结构控制摩擦轮（因为烧了上层结构板子所以就没弄）
2. 通讯部分 ：我现在用的时433模块做完发球信号用于调试 你把8266那部分写在自检函数里面吧 其他部分不会和它有冲突 
@mengmei-2000
3. 换场部分 这部分的ID号以及CAN中断 还有换场的代码我都写的差不多了（只有标志位部分还没写）
@varrage

**Comment by allensted** [comment]
> 主控的流程部分已经完全完成 并且已经测试时没有问题的 我已经上传到github上
> 现在还有三个地方没完成
> 
> 1. 上层结构控制摩擦轮（因为烧了上层结构板子所以就没弄）
> 2. 通讯部分 ：我现在用的时433模块做完发球信号用于调试 你把8266那部分写在自检函数里面吧 其他部分不会和它有冲突
>    @mengmei-2000
> 3. 换场部分 这部分的ID号以及CAN中断 还有换场的代码我都写的差不多了（只有标志位部分还没写）
>    @Varrage

我拆了一个舵轮底盘上的轮组主控（PR）现在第一个问题解决了
解决第一个问题唯一遇到的bug就是CAN通讯 只要有一个CAN 的过滤器设置的不对两个CAN都不能正常使用！

**Comment by allensted** [comment]
> 主控的流程部分已经完全完成 并且已经测试时没有问题的 我已经上传到github上
> 现在还有三个地方没完成
> 
> 1. 上层结构控制摩擦轮（因为烧了上层结构板子所以就没弄）
> 2. 通讯部分 ：我现在用的时433模块做完发球信号用于调试 你把8266那部分写在自检函数里面吧 其他部分不会和它有冲突
>    @mengmei-2000
> 3. 换场部分 这部分的ID号以及CAN中断 还有换场的代码我都写的差不多了（只有标志位部分还没写）
>    @Varrage

换场直接用串口（433模块）搞定就行 这个我加到我主控代码里面就可以了  现在第二个问题也解决了
