### ISSUE TITLE
TR代码整定

### ISSUE THREAD

**Issue by MUDloki** [UESTC-LIMIT/Progress-Management#16]
1.找鹏飞要代码
2.先整定主控 并且上传到github
3.整定四个轮组并且上传到github

**Comment by Varrage** [comment]
1、找鹏飞拿代码
      代码找鹏飞拿了，他的代码一个是主控代码，另一个是1号轮组的代码。他告诉我1号轮组和其他的不一样，他告诉我编码器方向是不一样的。

2、先整定主控 并且上传到github
      主控代码我把鹏飞的代码和陈敏浩的代码整合了一下，我基于鹏飞的代码把浩哥的路径部分放了进去，不过我通过版本管理，也确认了两个版本的不同，并把漏掉的注释补上了。
 
3、整定四个轮组并且上传到github
      整定的过程我没有跟着史老板，主要我觉得鹏飞都整完一轮了，我站在巨人的肩膀上应该还是比较轻松的，但实际上遇到了不少麻烦，有一些是车体设计上的问题，有些则是代码里莫名其妙的地方
         （1）2006滴滴叫的问题
           这个问题主要是轮组上的指针会卡在拨码开关上。如果指针碰到拨码开关，但没有完成初始化的时候，断电重启，拨码开关就会卡住轮组上的指针，所以无论发生什么，在启动前都要先转一下每个轮组，不要卡到指针。
        （2）轮组在初始化后左右摇摆
          轮组在编码器方向设置错误的情况（1变成-1）就会颤抖，原因应该是他无论怎么转，他的实际动作都和目标的相反。
       应该说，我基本上调好了，但我觉得有点怕，因为调的时候有些问题没有彻底解决，而且之前我也没有特别调过，所以还是有可能会有问题的，而究竟还要不要再改可能看后面的使用情况，我想在让他自动跑之前先加个遥控功能，遥控确认车子的情况，保证不会有什么其他问题再换全自动
