### ISSUE TITLE
pid的延迟问题

### ISSUE THREAD

**Issue by allensted** [UESTC-LIMIT/Progress-Management#23]
我在用webots调试一个差速小车的pid时，出现了延迟的问题 我发送的速度与实际电机的速度是不同的
（这里的原因是仿真帧数与运行帧数的不同）
![image.png](https://images.zenhubusercontent.com/5ebd15c7ac44f5dd8bb4da9e/ec2634a9-5832-43e5-84b9-f5004cd801ab)

对应我们现实调车，我觉得如果出现pid参数问题：
1.查看代码设置速度与实际速度的延迟差异是否很大
2.查看代码反馈延迟（编码器测速或者测距）与实际的延迟差异是否很大
3.检测代码逻辑
4.调参数

总之，不要盲目的调试参数并且花费大量的时间
=

**Comment by allensted** [comment]
大家可以看一下 之后我们遇到的问题或者说调试的心得等都可以写成这样的形式

**Comment by mengmei-2000** [comment]
🆗
