### ISSUE TITLE
确定通信内容、协议、时间节点

### ISSUE THREAD

**Issue by mengmei-2000** [UESTC-LIMIT/Progress-Management#29]
通信内容：
两车间同步信号量
采用惯导：
1、两车的相对位置
2、地盘角度（如果有需要的话）
采用视觉：
相机数据

需要协商解决的问题：
1、是采用惯导还是视觉
2、整个底盘的移动流程
3、采用视觉的话小主机与STM32的通信过程
4、两车之间的通信协议以及时间
@innns

**Comment by mouseInBasement** [comment]
# 2020.06.15 通信内容确定

## 通信内容
    主要是三个方面：相机数据、惯导坐标以及同步信号量
    但是相机数据和惯导坐标的传递必要性不大
    **惯导坐标**
    之前决定传递惯导坐标是为了能够在移动的过程之中完成抛接，现在采用定点抛接，惯导数据没有太大作用，不用传递
    **相机数据**
    视觉方面主要是用在接球的时候，通过相机回传橄榄球位置的数据形成闭环完成TR位置的微调。现在相机要是放在PR上面的话不仅要传递过去，TR在接收到之后还要进行坐标转换；要进行PID控制的话，橄榄球位置更新频率也需要很高，导致TR不停地进入DMA中断，可能会影响PID控制。因此，相机直接放在TR上面用串口和TR通信即可，相机数据也没有必要通过8266通信。
    **同步信号量**
    这个可以有，但是需要设计

## 通信协议
    通信的数据长度为10个字节，长度远大于需要的信号量个数，肯定能够满足需求

## 通信时间
    先到位的等待后到位的，依据实际情况决定。
    ** 问题 **
    先到为和后到位必须有严格的先后要求，以TR先到位为例，当TR先到位时，在信号量上等待，然后PR到位抛球，并发送信号量，TR接收到信号量之后处理橄榄球数据并进行PID调整。但是要是因为某些原因导致PR先到位抛球并发送信号量的话·，那么TR可能会在这个信号量上卡死。

## 与ucos的配合
    要是只需要传递信号量的话，还是挺容易的

**Comment by mouseInBasement** [comment]
# 2020.06.16 通信协议
共传递10B信息，前两B作为标识位，后8位作为数据位
格式如下：
**0x0001** 信号量帧
**0x0002** 其他帧
依据具体信号量的不同对数据位内容进行更改

**Comment by allensted** [comment]
这个信号量指的是开关信号量把。
我们现在的方案是PR上的摄像头传递橄榄球位置信息还是TR摄像头直接读取橄榄球偏移呢？
