### ISSUE TITLE
在底盘代码之中添加通信部分，并进行同步信号的发送测试

### ISSUE THREAD

**Issue by mengmei-2000** [UESTC-LIMIT/Progress-Management#31]

**Comment by mengmei-2000** [comment]
# 2020.06.15 通信内容确定

**Comment by mengmei-2000** [comment]
# 2020.06.16 通信协议
共传递10B信息，前两B作为标识位，后8位作为数据位
格式如下：
**0x0001** 信号量帧
**0x0002** 其他帧
依据具体信号量的不同对数据位内容进行更改

**Comment by mouseInBasement** [comment]
代码整合出现错误，应该是之前用的429，需要改几个寄存器
