### ISSUE TITLE
PR上层结构优化

### ISSUE THREAD

**Issue by allensted** [UESTC-LIMIT/Progress-Management#33]
1. 将底盘与上层结构拆除，单独测试底盘的情况，找出问题修复
底盘测试发现四个轮子都不太稳定。一方面应该是螺丝松动，这个上紧就好，另一方面可能全向轮发生了变形。

2.在底盘调试路径期间熟悉和改进老牛的上层结构
王老板6月13号寄回的零件里面老牛设计的摩擦轮由于疫情原因没有包胶。所以只好找淘宝店家直接做四个轮子然后包胶好发回来。

6月14看了老牛的摩擦轮之后，主要考虑其固定方法。今天开雕刻机遇到电脑打不开的情况，不同于上学期按了F1再按Esc就可以开机，电脑不管怎么弄都最多光标闪烁，帅学长把硬盘插稳了就可以启动了。遇到开机不能启动我的经验是：一般都是硬件问题（主要是两类：一是灰尘；二是硬盘没插稳）；如果以后用久了之后我觉得可能会出现CMOS电池电源不足，也会出现光标闪烁，或者是硬盘没有被选为最先的启动设备。

6月15、16
把上层结构的零件都用雕刻机雕了，但是上层结构的孔都太小，这应该是我用的玉米铣刀的问题。这个玉米铣刀的直径应该才1.5mm，队里的玉米铣刀紧缺，直刀也缺。我已经叫张闯购买。上层结构拼好后，发现大小与圆上层摩擦轮炮台的尺寸有差异，安装不到车上。商量后决定修改上层结构的尺寸，做一版和原结构尺寸类似的摩擦轮倾斜的上层机构。设计时注意摩擦轮的间距。

6月17
安装上层机构到车上。新上层结构的宽度与原上层结构的宽度是一模一样的，但是安装好后，发现上层结构的宽度与两根铝管之间的宽度不是完全一样的，中间有空隙。同时，球实际上不是完全对心的，与上层结构的中心有一点偏差，这说明原机构其实并没有完全对心。

**Comment by allensted** [comment]
@yangjinyu123 爪子碰到触控开关的位置时 会卡住摩擦轮 得调整一下爪子或者触控开关的位置

**Comment by yangjinyu123** [comment]
爪子和触碰开关位置没有变，是匹配当前的发射角度的。最好的改进方法应该是调整两个固定赛钢与侧面连接的孔洞的位置，或者将赛钢反装。 @allensted

**Comment by yangjinyu123** [comment]
@allensted 要修的话最好搬回基地修理，不过确实比较麻烦
